# yaml-language-server: $schema=https://json.schemastore.org/github-action.json
name: "Test Composite Workflow"
description: "test"

inputs:
  debug:
    description: 'whether prints envs or not'
    required: false
    default: 'false'
env:
  CACHE_KEY_PREFIX="-zdpk-actions-scripts"

runs:
  using: composite
  steps:
    - id: meta
      shell: bash
      env:
        ACTION_REPO: ${{ github.action_repository }}
        ACTION_REF: ${{ github.action_ref }}
        ACTION_PATH: ${{ github.action_path }}
        DEBUG: ${{ inputs.debug }}
      run: |
        set -euo pipefail

        if [[ "$DEBUG" == 'true' ]]; then
          echo "GITHUB_WORKSPACE          : $GITHUB_WORKSPACE"
          echo "github.workspace          : ${{ github.workspace }}"
          echo "ACTION_REF                : $ACTION_REF"
          echo "GITHUB_ACTION_PATH        : $GITHUB_ACTION_PATH"
          echo "ACTION_PATH               : $ACTION_PATH"
        fi

        if ! command -v sha256sum >/dev/null 2>&1; then
          echo "`sha256sum` doesn't exist"
          exit 1
        fi

        # 1) if `action_ref` is not sha, replace to hashed content  
        if [[ -n "$ACTION_REF" && "$ACTION_REF" =~ ^[0-9A-Fa-f]{40}$ ]]; then
          digest="$ACTION_REF"
        else
          # exclude metadata
          digest="$(
            ( cd "$ACTION_PATH" \
              && find . -type f -not -path './.git/*' -print0 \
              | LC_ALL=C sort -z \
              | xargs -0 sha256sum \
              | sha256sum \
              | cut -c1-16 )
          )"
          ACTION_DIGEST="content-$digest"
        fi

        # owner/repo -> owner-repo
        repo_slug="${ACTION_REPO//\//-}"

        cache_key="$CACHE_KEY_PREFIX-$repo_slug-$digest"
        scripts_dir="$GITHUB_WORKSPACE/$ACTION_REPO/scripts"

        mkdir -p "$scripts_dir"

        echo "scripts-dir=$scripts_dir" >> "$GITHUB_OUTPUT"
        echo "cache-key=$cache_key" >> "$GITHUB_OUTPUT"

        if [[ "$DEBUG" == 'true' ]]; then
          echo "digest                    : $digest"
          echo "repo_slug                 : $repo_slug"
          echo "cache_key                 : $cache_key"
          echo "scripts_dir               : $scripts_dir"
        fi
          
    # - name: check cache includes util scripts
    #   id: cache
    #   uses: actions/cache/restore@v4
    #   with:
    #     path: util
    #     key: util
    #     restore-keys: util
        
    # - name: fetch actions scripts
    #   shell: bash
    #   run: |
    #     git clone https://github.com/zdpk/actions
    #     chmod +x actions
    #     echo "${{ github.ref }}"


  
