name: Sync Obsidian Blog

on:
  workflow_call:
    inputs:
      dest-repository:
        type: string
        required: true

      dest-ref:
        type: string
        required: false
        default: main

      src-dir:
        type: string
        required: false
        default: content/posts

      src-post-dir:
        type: string
        required: false
        default: post

      src-attachment-dir:
        type: string
        required: false
        default: attachment

      dest-post-dir:
        type: string
        required: false
        default: pages

      dest-attachment-dir:
        type: string
        required: false
        default: public/images

    secrets:
      # secrets for target repo
      github-pat:
        required: true

# prevent concurrent runs on the same ref in the same repo
concurrency:
  group: sync-posts-${{ github.ref }}
  # queueing
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      # source/dest repos
      # 1. checkout current repo
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: main
          # for detecting changes
          fetch-depth: 2
          path: source

      # # 2. checkout dest repo
      # - name: Checkout dest repository
      #   uses: actions/checkout@v4
      #   with:
      #     repository: ${{ inputs.dest-repo }}
      #     ref: ${{ inputs.dest-ref }}
      #     # for detecting changes
      #     path: dest

      # 2. rsync
      - name: Detect changes in content/
        id: diff
        working-directory: ./source
        run: |
          if git diff --queit HEAD~1 HEAD -- '${{ inputs.src-post-dir }}' '${{ inputs.src-attachment-dir }}'; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi

          # local before="${{ github.event.before }}"
          # local after="${{ github.sha }}"

          # if [[ "$before" == "0000000000000000000000000000000000000000" || -z "$before" ]]; then
          #   before=$(git hash-object -t tree /dev/null)
          # fi

          # git fetch --no-tags origin "$before" "$after" >/dev/null 2>&1 || true
          # if git diff

      # 2. sparse checkout src repo to copy files
      - name: Checkout dest repository
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.dest-repository }}
          ref: ${{ inputs.dest-ref }}
          fetch-depth: 1
          path: dest

      # 3. apply rsync
      - name: Apply rsync posts
        if: steps.diff.outputs.changed == 'true'
        run: |
          rsync -avh --delete \
            --exclude='.obsidian/' \
            --exclude='.DS_Store' \
            ./source/${{ inputs.src-post-dir }} ./dest/${{ inputs.dest-post-dir }}

      - name: Apply rsync attachments
        if: steps.diff.outputs.changed == 'true'
        run: |
          mkdir -p ./dest/${{ inputs.dest-attachment-dir }}

          rsync -avh --delete \
            --exclude='.obsidian/' \
            --exclude='.DS_Store' \
            ./source/${{ inputs.src-attachment-dir }} ./dest/${{ inputs.dest-attachment-dir }}

      - name: Commit and Push
        if: steps.diff.outputs.changed == 'true'
        working-directory: ./dest
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            exit 0
          fi

          git add -A
          if git diff --cached --quiet; then
            echo "No staged changes to commit"
            exit 0
          fi

          git remote set-url origin \
            "https://x-access-token:${{ secrets.github-pat }}@github.com/${{ inputs.dest-repository }}.git"

          git commit -m "chore(posts): sync from vault @ $GITHUB_SHA"
          git push origin HEAD:${{ inputs.dest-ref }}
