name: Test Actions

on:
  workflow_dispatch:
    
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Use local composite action
        uses: zdpk/actions/setup-utils@main
        with:
          A: "1"
